# Generated by Django 5.0.2 on 2025-10-21 09:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sampleapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Worker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("job", models.IntegerField()),
            ],
        ),
    ]
