# Generated by Django 5.0.2 on 2025-11-03 08:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sampleapp", "0004_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("phone", models.IntegerField()),
                ("email", models.EmailField(max_length=255)),
            ],
        ),
    ]
