# Generated by Django 5.0.2 on 2025-11-03 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sampleapp", "0005_author"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book_s",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("book_name", models.CharField(max_length=255)),
                (
                    "author_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sampleapp.author",
                    ),
                ),
            ],
        ),
    ]
