# Generated by Django 5.0.2 on 2025-11-14 08:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sampleapp", "0007_trainer"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bookss",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("author", models.CharField(max_length=100)),
                ("summary", models.TextField()),
                ("isbn", models.CharField(max_length=13, unique=True)),
            ],
        ),
    ]
