# Generated by Django 5.0.2 on 2025-11-14 09:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sampleapp", "0008_bookss"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="student",
            table="Student",
        ),
    ]
