# Generated by Django 5.0.2 on 2025-11-18 08:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sampleapp", "0009_alter_student_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="work",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "male"),
                            ("female", "female"),
                            ("others", "others"),
                        ],
                        max_length=6,
                    ),
                ),
            ],
        ),
    ]
